default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  reconnect: true
  pool: 5
  host:     <%= Settings.mysql.host %>
  database: <%= Settings.mysql.database %>
  username: <%= Settings.mysql.username %>
  password: <%= Settings.mysql.password %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
